---
vagrantfile:
  vm:
    box: wheezy64
    box_url: http://dl.dropbox.com/u/937870/VMs/wheezy64.box
    memory: '2048'
    cpus: '2'
    chosen_provider: virtualbox
    network:
      private_network: 10.22.22.10
      forwarded_port:
        rGZvl2wILi9e:
          host: '7668'
          guest: '22'
    hostname: 'aegir.dev'
    short_name: 'contrib'
    long_name: 'Contrib Aegir Dev Env'
    aegir_user:
      uid: '998'
      gid: '999'
    shared_dirs:
      sources:
        source: sources
        target: /var/aegir/sources
      builds:
        source: builds
        target: /var/aegir/shared_platforms
      exports:
        source: exports
        target: /var/aegir/migrations
      logs:
        source: logs
        target: /var/aegir/logs
aegir:
  hostmaster:
    url: http://git.drupal.org/project/hostmaster.git
    ref: 7.x-3.x
  provision:
    url: http://git.drupal.org/project/provision.git
    ref: 7.x-3.x
  makefile:
  web_server: apache2
  platform_path: /var/aegir/hostmaster
